apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
  labels:
    app: opencost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencost
  template:
    metadata:
      labels:
        app: opencost
    spec:
      containers:
      - name: opencost
        image: opencost/opencost:latest
        ports:
        - containerPort: 9003
        env:
        - name: PROMETHEUS_SERVER
          value: "http://prometheus-server:9090"
---
apiVersion: v1
kind: Service
metadata:
  name: opencost
spec:
  selector:
    app: opencost
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
  type: ClusterIP